BAZ-17/searchBar
Re-boot-Coding-Bootcamp/Bazaar pull request #2
Opened 2024-04-09 20:56 UTC by BaburDilshat

BAZ-17/searchBar
Link to Story
https://re-boot.atlassian.net/browse/BAZ-17

Description
Worked on search bar

Screenshot(s) / GIF(s):
<img width="993" alt="image" src="https://github.com/Re-boot-Coding-Bootcamp/Bazaar/assets/158536270/98035516-4d28-4ed3-b92f-1b39b52451b5">

Type of change
 Bug fix
 New feature
 Dependency / Configuration update
 Documentation update
Checklist:
 My code follows the project's style guidelines
 I have created a Storybook story for my component(s)
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have made corresponding changes to the documentation
 My changes generate no new warnings
 I have added tests that prove my fix is effective or that my feature works
 New and existing unit tests pass locally with my changes

2024-04-10 21:51 UTC, Jack-Vu reviewed
Looks pretty good so far, but you might need to handle the enter key since it is an input field

2024-04-11 15:27 UTC, Jack-Vu requested changes
A few changes needed

2024-04-11 15:27 UTC, Jack-Vu commented on src/app/_components/SearchBar/DesktopSearchBar.tsx
> +  const handlerFuntion = () => {
this function and onSubmit do the same thing

2024-04-11 15:27 UTC, Jack-Vu commented on src/app/_components/SearchBar/MobileSearchBar.stories.tsx
> +// import { Sample } from "./MobileSearchBar";
remove this comment

2024-04-11 15:28 UTC, Jack-Vu reviewed
Also need to resolve conflict with dev branch

2024-04-11 22:09 UTC, Muradil-Erkin approved these changes, later dismissed

2024-04-11 22:16 UTC, Muradil-Erkin approved these changes

2024-04-11 22:16 UTC, merged